# Generated by Django 4.0 on 2022-02-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('cantact_number', models.IntegerField()),
                ('police_type', models.CharField(choices=[('PO', 'Police Officer'), ('EC', 'Entry Clerk')], max_length=16)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police', to='addresses.address')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=64)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policeStation', to='addresses.address')),
                ('entry_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationClerk', to='Police.police')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationOfficer', to='Police.police')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policeStationArea', to='Police.policestation')),
            ],
        ),
    ]
