# Generated by Django 4.0 on 2022-02-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=64)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('Crime', 'crime'), ('Missing Person', 'missing person')], max_length=16)),
                ('location', models.CharField(max_length=64)),
                ('Reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reporter', to='Reports.reporter')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_Name', models.CharField(max_length=64)),
                ('Description', models.TextField(blank=True, max_length=364, null=True)),
                ('status', models.CharField(choices=[('Founded', 'founded'), ('Still Missing', 'still missing')], max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_person_report', to='Reports.report')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_address', to='addresses.address')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, max_length=364, null=True)),
                ('crime_status', models.CharField(choices=[('Wanted', 'wanted'), ('Arrested', 'arrested')], max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='Reports.crime')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Reports.report')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='report',
            field=models.ManyToManyField(through='Reports.CrimeReport', to='Reports.Report'),
        ),
    ]
